import "./globals.css";
import { Inter } from "next/font/google";
import Cabecalho from "@/components/cabecalho/cabecalho";
import Rodape from "@/components/rodape/rodape";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "4° Entrega - Challenge",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className="reset">
        <Cabecalho />
          {children}
        <Rodape />
      </body>
    </html>
  );
}
